name: 'Get count of issues in repo'
description: 'Returns amount of open/closed PRs/issues in the repository based on action-mode'
author: 'Yuri Skorokhodov'
inputs:
  action-mode:
    description: Can be 'issues', 'issues-open', 'issues-closed', 'issues-opened-since-date'
    required: true
    default: 'issues'
  issues-from-date:
    description: Used in case of 'issues-opened-since-date' mode, in such case returns amount of issues created from the date. This is a timestamp in ISO 8601 format
    required: false
outputs:
  answer:
    description: 'Amount of PRs/issues in the repository based on chosen action-mode'
runs:
  using: 'node16'
  main: 'dist/index.js'
