name: 'Repo issues counter'
description: 'Returns amount of open/closed PRs/issues in the repository based on action-mode'
author: 'Yuri Skorokhodov'
inputs:
  action-mode:
    required: true
    description: Can be 'issues-all', 'issues-open', 'issues-closed', 'issues-opened-since-date'
    default: 'issues-all'
  issues-from-date:
    required: false
    description: Used in case of 'issues-opened-since-date' mode, in such case returns amount of issues created from the date. This is a timestamp in ISO 8601 format
  repo:
    required: true
    description: Name of the repository
  owner:
    required: true
    description: User or the organization name
outputs:
  answer:
    description: 'Amount of PRs/issues in the repository based on chosen action-mode'
runs:
  using: 'node16'
  main: 'dist/index.js'
